version: '3.8'

services:
  # Servicio de la base de datos PostgreSQL
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: api_database
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de la aplicación Laravel
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    depends_on:
      - postgres_db
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_DATABASE: api_database
      DB_USERNAME: api_user
      DB_PASSWORD: secret
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  # Servicio de Nginx como proxy reverso
  nginx_server:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    depends_on:
      - laravel_app
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:

